[workspace]
members = [
    "extensions/org.shilpo.wallpaper",
    "extensions/org.shilpo.weather",
    "extensions/io.github.alice.world-clock",
]
exclude = [
    "crates/generator",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
publish = false

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wit-bindgen = "0.60"
shilpo-ext-sdk = { git = "https://github.com/shilpo-rs/sdks", rev = "c48c0f0c8736d7398d0b091d1f23f63963d9f897" }
