#!/usr/bin/env bash
#
# A wizard walks a human through setting up Ed25519 signing keys and GitHub Actions environment secrets.
# Generated by the /wizard skill for shilpo-rs/extensions.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the setup; this wizard guides key generation and securely configures\n' "$DIM"
  printf '  GitHub Actions protected environment secrets for shilpo-rs/extensions.\n'
  printf '  Stop any time with Ctrl-C.%s\n\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --repo "${TARGET_REPO:-shilpo-rs/extensions}" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_env_secret ENV_NAME SECRET_NAME VALUE sets a secret in a specific GitHub Actions environment.
set_env_secret() {
  local env_name="$1" name="$2" value="$3"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --env "$env_name" --repo "${TARGET_REPO:-shilpo-rs/extensions}" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("Environment '$env_name' secret: $name")
      printf '  %s✓ set%s GitHub environment (%s) secret %s\n' "$GREEN" "$RESET" "$env_name" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub environment '$env_name' secret $name (set manually in Settings → Environments → $env_name)")
  warn "skipped GitHub environment secret $name in $env_name: set it manually"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Shilpo Extension Registry: Cryptographic Key Setup"

# ── Stage 1: GitHub Repository & Environment ──────────────────────────────
stage "Verify Target Repository and Environment"
say "We will configure secrets for the privileged publication workflow in shilpo-rs/extensions."
ask TARGET_REPO "Target GitHub repository [default: shilpo-rs/extensions]:"
TARGET_REPO="${TARGET_REPO:-shilpo-rs/extensions}"
say "Target repo: $TARGET_REPO"
open_url "https://github.com/$TARGET_REPO/settings/environments"
step "In GitHub Settings → Environments, make sure an environment named 'production' exists."
step "Add protection rules (such as Required Reviewers or branch protection for 'main') as desired."
pause "Press Enter once the 'production' environment is ready on GitHub."

# ── Stage 2: Index Signing Key ───────────────────────────────────────────
stage "Generate or Provide INDEX_SIGNING_KEY"
say "The INDEX_SIGNING_KEY signs the canonical index.json in the protected publication environment."
if confirm "Would you like to automatically generate a fresh Ed25519 keypair now?"; then
  KEYPAIR=$(python3 -c '
import os, base64
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.hazmat.primitives import serialization

priv = ed25519.Ed25519PrivateKey.generate()
priv_bytes = priv.private_bytes(
    encoding=serialization.Encoding.Raw,
    format=serialization.PrivateFormat.Raw,
    encryption_algorithm=serialization.NoEncryption()
)
pub_bytes = priv.public_key().public_bytes(
    encoding=serialization.Encoding.Raw,
    format=serialization.PublicFormat.Raw
)
print(base64.b64encode(priv_bytes).decode("ascii") + " " + base64.b64encode(pub_bytes).decode("ascii"))
' 2>/dev/null || true)

  if [[ -n "$KEYPAIR" ]]; then
    INDEX_SIGNING_KEY=$(echo "$KEYPAIR" | awk '{print $1}')
    INDEX_PUBLIC_KEY=$(echo "$KEYPAIR" | awk '{print $2}')
    printf '  %s✓ Generated new Ed25519 Index Keypair%s\n' "$GREEN" "$RESET"
    printf '  %sPublic Key (OFFICIAL_ROOT_PUBLIC_KEY):%s %s\n\n' "$BOLD" "$RESET" "$INDEX_PUBLIC_KEY"
  else
    warn "python3-cryptography not installed; please paste your Base64 Ed25519 private key."
    ask_secret INDEX_SIGNING_KEY "Paste INDEX_SIGNING_KEY (Base64):"
  fi
else
  ask_secret INDEX_SIGNING_KEY "Paste existing INDEX_SIGNING_KEY (Base64):"
fi

if [[ -n "$INDEX_SIGNING_KEY" ]]; then
  set_env_secret "production" "INDEX_SIGNING_KEY" "$INDEX_SIGNING_KEY"
fi

# ── Stage 3: Package Signing Key ─────────────────────────────────────────
stage "Generate or Provide PACKAGE_SIGNING_KEY"
say "The PACKAGE_SIGNING_KEY signs .shilpo-ext packages and release manifests."
if confirm "Would you like to automatically generate a fresh Ed25519 package keypair now?"; then
  PKG_KEYPAIR=$(python3 -c '
import os, base64
from cryptography.hazmat.primitives.asymmetric import ed25519
from cryptography.hazmat.primitives import serialization

priv = ed25519.Ed25519PrivateKey.generate()
priv_bytes = priv.private_bytes(
    encoding=serialization.Encoding.Raw,
    format=serialization.PrivateFormat.Raw,
    encryption_algorithm=serialization.NoEncryption()
)
pub_bytes = priv.public_key().public_bytes(
    encoding=serialization.Encoding.Raw,
    format=serialization.PublicFormat.Raw
)
print(base64.b64encode(priv_bytes).decode("ascii") + " " + base64.b64encode(pub_bytes).decode("ascii"))
' 2>/dev/null || true)

  if [[ -n "$PKG_KEYPAIR" ]]; then
    PACKAGE_SIGNING_KEY=$(echo "$PKG_KEYPAIR" | awk '{print $1}')
    PACKAGE_PUBLIC_KEY=$(echo "$PKG_KEYPAIR" | awk '{print $2}')
    printf '  %s✓ Generated new Ed25519 Package Keypair%s\n' "$GREEN" "$RESET"
    printf '  %sPackage Public Key:%s %s\n\n' "$BOLD" "$RESET" "$PACKAGE_PUBLIC_KEY"
  else
    warn "python3-cryptography not installed; please paste your Base64 Ed25519 private key."
    ask_secret PACKAGE_SIGNING_KEY "Paste PACKAGE_SIGNING_KEY (Base64):"
  fi
else
  ask_secret PACKAGE_SIGNING_KEY "Paste existing PACKAGE_SIGNING_KEY (Base64):"
fi

if [[ -n "$PACKAGE_SIGNING_KEY" ]]; then
  set_env_secret "production" "PACKAGE_SIGNING_KEY" "$PACKAGE_SIGNING_KEY"
fi

# ── Stage 4: Verification & Confirmation ─────────────────────────────────
stage "Review Configuration"
say "GitHub Actions secrets have been configured for the protected 'production' environment."
step "Visit GitHub Settings → Environments → production to verify secrets are set."
open_url "https://github.com/$TARGET_REPO/settings/environments"
pause "Press Enter to finish setup."

finish
